# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [40]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

heightNumpy = np.array(height)
weightNumpy = np.array(weight)

BMI = (weightNumpy / (heightNumpy ** 2)) * 730 
for index in BMI:
    print(f'BMI - {index}')

BMI - 16.866204578869986
BMI - 17.877551020408163
BMI - 18.825629835350128
BMI - 19.714506172839506
BMI - 20.54794520547945
BMI - 21.329437545653764
BMI - 22.06222222222222


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [30]:
def theMatrix(start, stop, shape = (np.random.randint(2,4), np.random.randint(2,4)), data_type = int):
    if data_type != float:
        return np.random.randint(start, stop, shape)
    else:
        return np.random.uniform(start, stop, shape)

print(theMatrix(0,6))
print(f'\n {theMatrix(0,6, (3, 3), data_type= float)}')

[[0 0 5]
 [2 1 2]]

 [[4.36822166 2.48662466 3.94718455]
 [2.07196307 0.84494242 2.88540352]
 [2.02342989 2.79623611 5.16538353]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [37]:
import csv
import numpy as np
import statistics



In [38]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

rs2017 = load_data('redsox_2017_hitting.txt')
rs2018 = load_data('redsox_2018_hitting.txt')

all_slg2017 = rs2017['SLG']
all_slg2018 = rs2018['SLG']

slg2017 = np.array(all_slg2017)
slg2018 = np.array(all_slg2018)

meanslg2017 = statistics.mean(slg2017)
meanslg2018 = statistics.mean(slg2018)

print('SLG for 2017')
print(meanslg2017)
print('\nSLG for 2018')
print(meanslg2018)



SLG for 2017
0.39334783

SLG for 2018
0.38750002
